/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'tertiary': '#ffb786',
        'secondary': '#4edea3',
        'tertiary-fixed-dim': '#ffb786',
        'on-error-container': '#ffdad6',
        'inverse-on-surface': '#313030',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-primary': '#002e6a',
        'tertiary-fixed': '#ffdcc6',
        'surface-variant': '#353534',
        'on-secondary-fixed-variant': '#005236',
        'surface': '#131313',
        'on-secondary': '#003824',
        'on-background': '#e5e2e1',
        'on-secondary-container': '#00311f',
        'on-primary-container': '#00285d',
        'primary-fixed': '#d8e2ff',
        'on-tertiary-fixed-variant': '#723600',
        'surface-container': '#201f1f',
        'primary-container': '#4d8eff',
        'on-tertiary-container': '#461f00',
        'surface-dim': '#131313',
        'on-primary-fixed': '#001a42',
        'error': '#ffb4ab',
        'surface-tint': '#adc6ff',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary': '#502400',
        'primary': '#adc6ff',
        'tertiary-container': '#df7412',
        'on-primary-fixed-variant': '#004395',
        'on-secondary-fixed': '#002113',
        'background': '#131313',
        'inverse-primary': '#005ac2',
        'outline-variant': '#424754',
        'on-error': '#690005',
        'secondary-container': '#00a572',
        'outline': '#8c909f',
        'inverse-surface': '#e5e2e1',
        'primary-fixed-dim': '#adc6ff',
        'on-tertiary-fixed': '#311400',
        'secondary-fixed-dim': '#4edea3',
        'on-surface': '#e5e2e1',
        'error-container': '#93000a',
        'surface-bright': '#393939',
        'surface-container-low': '#1c1b1b',
        'on-surface-variant': '#c2c6d6',
        'secondary-fixed': '#6ffbbe',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'lg': '48px',
        'xl': '96px',
        'gutter': '24px',
        'base': '8px',
        'sm': '12px',
        'container-max': '1200px',
        'md': '24px',
        'xs': '4px',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
}
